version: '3.9'
services:
  app:
    build:
      context: .
    image: newbotksenia:latest
    container_name: newbotksenia
    env_file:
      - .env
    environment:
      - PORT=${PORT:-3000}
      - MONGO_URI=${MONGO_URI:-mongodb://mongo:27017/newbotksenia}
      - N8N_TOKEN=${N8N_TOKEN}
      - YANDEX_GEOCODER_API_KEY=${YANDEX_GEOCODER_API_KEY}
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mongo_data:


